# Alacritty config file - andrian
[window]
opacity = 0.95
decorations = "full"
dynamic_padding = true

[window.dimensions]
columns = 80
lines = 25

[window.padding]
x = 4
y = 4

[font]
size = 10.0

[font.normal]
family = "Fantasque Sans Mono"
style = "Regular"

[font.bold]
family = "Fantasque Sans Mono"
style = "Bold"

[font.italic]
family = "Fantasque Sans Mono"
style = "Italic"

[cursor.style]
shape = "Block"
blinking = "On"

[scrolling]
history = 10000
multiplier = 3

[colors.primary]
foreground = "#d3c6aa"
background = "#2d353b"

[colors.cursor]
text = "#2d353b"
cursor = "#d3c6aa"

[colors.selection]
text = "#d3c6aa"
background = "#414b51"

[colors.normal]
black = "#343f44"
red = "#e67e80"
green = "#a7c080"
yellow = "#dbbc7f"
blue = "#7fbbb3"
magenta = "#d699b6"
cyan = "#83c092"
white = "#d3c6aa"

[colors.bright]
black = "#859289"
red = "#e67e80"
green = "#a7c080"
yellow = "#dbbc7f"
blue = "#7fbbb3"
magenta = "#d699b6"
cyan = "#83c092"
white = "#d3c6aa"
